=== icocowen/ywj/src/main/java/cn/ywj/www/util/db/questionnaire_models.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.ywj.cn/questionnaire-model" targetNamespace="http://www.ywj.cn/questionnaire-model" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="questionnaire_models" type="questionnaire_models_type"/>
	<xs:element name="questionnaire_model" type="questionnaire_model_type"/>
	<xs:element name="question_num" type="xs:integer"/>
	<xs:element name="questions" type="questions_type"/>
	<xs:element name="question" type="question_type" />
	
	<xs:element name="item">
		<xs:complexType mixed="true" >
			<xs:attribute name="option" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="question_type">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:element ref="item"/>
		</xs:sequence>
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="radio"/>
					<xs:enumeration value="checkbox"/>
					<xs:enumeration value="text"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string"/>
		<xs:attribute name="use" type="xs:boolean" default="true"/>
		<xs:attribute name="length" type="xs:integer"/>
	</xs:complexType>
	
	<xs:complexType name="questionnaire_model_type">
		<xs:sequence>
			<xs:element ref="question_num"/>
			<xs:element ref="questions"/>
		</xs:sequence>
		<xs:attribute name="questionnaire_id" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="questions_type">
		<xs:sequence maxOccurs="unbounded">
			<xs:element ref="question"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="questionnaire_models_type">
		<xs:sequence maxOccurs="unbounded">
			<xs:element ref="questionnaire_model"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== icocowen/ywj/src/main/java/cn/ywj/www/util/db/questionnaire_models.xml
<?xml version="1.0" encoding="UTF-8"?>
<questionnaire_models xmlns="http://www.ywj.cn/questionnaire-model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ywj.cn/questionnaire-model questionnaire_models.xsd">
	<questionnaire_model  questionnaire_id="21331">
		<question_num>3</question_num>
		<questions>
			<question type="radio" value="你喜欢什么口味的粽子？" use="true">
				<item option="a" >甜味粽</item>
				<item option="b" >咸味粽</item>
				<item option="c" >辣味粽</item>
			</question>
			<question type="checkbox" value="你吃过什么味的粽子？" use="true">
				<item option="a" >甜味粽</item>
				<item option="b" >咸味粽</item>
				<item option="c" >辣味粽</item>
			</question>
			<question type="text" value="你吃粽子的感受是什么？" use="false" length="20"/>
		</questions>
	</questionnaire_model>
	
</questionnaire_models>
