=== icocowen/ywj/src/main/java/cn/ywj/www/util/db/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" targetNamespace="http://www.ywj.cn/users" xmlns="http://www.ywj.cn/users">
	<xs:element name="users" type="users_type"/>
	<xs:element name="user" type="user_type"/>
	<xs:element name="email">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value=".*@{1}.*"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="password">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="nickname" type="xs:string"/>
	<xs:element name="motto" type="xs:string"/>
	<xs:element name="phone_num">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[1-9]{1}[0-9]{10}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="avatar" type="xs:string"/>
	<xs:element name="register_date" type="xs:string"/>
	<xs:element name="last_login_date" type="xs:string"/>

	<xs:complexType name="users_type">
		<xs:sequence maxOccurs="unbounded">
			<xs:element ref="user"/>
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:complexType name="user_type" >
		<xs:all maxOccurs="1" minOccurs="1">
			<xs:element ref="email" />
			<xs:element ref="password" />
			<xs:element ref="nickname" />
			<xs:element ref="motto" />
			<xs:element ref="phone_num" />
			<xs:element ref="avatar" />
			<xs:element ref="register_date" />
			<xs:element ref="last_login_date" />
		</xs:all>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="type" type="xs:string" use="required"/>
	</xs:complexType>
</xs:schema>

=== icocowen/ywj/src/main/java/cn/ywj/www/util/db/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users  xmlns="http://www.ywj.cn/users" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ywj.cn/users users.xsd">
	<user id="2003" type="2">   <!--type 1 为会员用户，2为普通用户 -->
		<email>1558165507@qq.com</email>
		<password>$2a$10$YUthO3FOocQFxBgMMke2ROV2MKqAJwHEb8VeVhgcy4oZkx5S/zTHm</password> <!--123456 -->
		<nickname>iwen</nickname>
		<motto>今日事几日闭</motto>
		<phone_num>15119306877</phone_num>
		<avatar>/images/avatar.jpg</avatar>
		<register_date>1560047957</register_date>
		<last_login_date>1560047957</last_login_date>
	</user>
</users>
